name: breaking-nomad

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'
      - name: test
        run: make test
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'
      - name: build
        run: make publish

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist/BreakingNomad.Ui'
          name: github-pages

      - name: Deploy production to Netlify
        uses: South-Paw/action-netlify-deploy@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: './dist/BreakingNomad.Ui'
          comment-on-commit: true
         
      
